# Generated by Django 3.2.13 on 2022-06-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='select',
            table='select',
        ),
    ]
