# Generated by Django 3.2.13 on 2022-06-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_select_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.DeleteModel(
            name='UserAddressBook',
        ),
    ]
