# Generated by Django 3.2.13 on 2022-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220629_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'addressb',
            },
        ),
    ]
